name: example
description: route_generator Flutter example project.
version: 1.1.0

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  route_annotation: ^0.1.0
  example_library:
    path: ../example_library

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.5.0
  route_generator:
    path: ../route_generator

flutter:

  uses-material-design: true
