name: interceptor
description: A starting point for Dart libraries or applications.
version: 0.0.1
author: microtears <microtears@gmail.com>
homepage: https://github.com/microtears/route_generator_repo
publish_to: none

environment:
  sdk: '>=2.2.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
