builders:
  route_builder:
    import: "package:route_generator/builder.dart"
    builder_factories: ["routeBuilder"]
    build_extensions: { ".dart": ["*.route.dart"] }
    auto_apply: dependents
    build_to: source