builders:
  route_builder:
    import: 'package:route_generator/builder.dart'
    builder_factories: ['routeBuilder']
    build_extensions: { '.dart': ['route_generator.route.dart'] }
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
    build_to: source
  route_collector:
    import: 'package:route_generator/builder.dart'
    builder_factories: ['routeCollector']
    build_extensions: { '.dart': ['route_generator.collector.dart'] }
    auto_apply: dependents
    applies_builders: ["source_gen|combining_builder"]
    runs_before: ["route_generator|route_builder"]
    build_to: cache