name: route_generator
description: This is a route generation library.Only a small amount of code is required,then use the annotation to match the source code generation, automatically generate the routing table.
version: 1.0.0
author: microtears <microtears@gmail.com>
homepage: https://github.com/microtears/route_generator_repo

publish_to: none

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  source_gen: ^0.9.7+1
  route_annotation: ^0.2.1
  analyzer: ^0.40.4
  build: ^1.5.0

dev_dependencies:
  build_runner: ^1.10.3

dependency_overrides:
  route_annotation:
    path: ../route_annotation
