name: route_annotation
description: The route_annotation library is annotated with the route_generator library. For more details, see the introduction of the route_generator library and the Dart documentation.
version: 0.2.1
author: microtears <microtears@gmail.com>
homepage: https://github.com/microtears/route_generator_repo
publish_to: none

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  interceptor: ^0.0.1

dependency_overrides:
  interceptor:
    path: ../interceptor

flutter: