name: route_annotation
description: The route_annotation library is annotated with the route_generator library. For more details, see the introduction of the route_generator library and the Dart documentation.
version: 0.2.0
author: microtears <microtears@gmail.com>
homepage: https://github.com/microtears/route_generator_repo

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: